In [69]:
import numpy as np
import sys

In [107]:
array.size

10

In [115]:
N = 10
array = np.array([[1,1], [2,2], [3,3]])
print(array, '\n')

Total = array.size



Divisor = 3
Parcela = 3
Faixa = Total // Divisor

print('Total:', Total, '\tDivisor: ', Divisor, '\tParcela: ', Parcela, '\tFaixa: ', Faixa, '\n')


[[1 1]
 [2 2]
 [3 3]] 

Total: 6 	Divisor:  3 	Parcela:  3 	Faixa:  2 



In [119]:
array[1:3]

array([[2, 2],
       [3, 3]])

In [117]:
array.shape

(3, 2)

In [121]:
valor = array.shape[0]
valor

3

In [104]:
id(array)

1764599222256

In [105]:
id(array.copy)

1764604272752

In [103]:
Inicio = (Parcela - 1) * Faixa
Final = Inicio + Faixa
print('Inicio: ', Inicio, 'Final: ', Final, '\n')
x_train = x_train_full[Inicio : Final].copy()
y_train = y_train_full[Inicio : Final].copy()

Inicio:  6 Final:  9 



array([6, 7, 8])

Inicio:  6 Final:  10 



array([6, 7, 8, 9])

In [68]:
parcial = array[Inicio:Final]
parcial

array([3, 4, 5, 6])

In [65]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])